
<nav class="navbar navbar-expand-lg navbar-dark bg-dark p-3 sticky-top">
  <div class="container-fluid">
    <a class="titlet navbar-brand" href="#">Leonard Euler</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarScroll"
      aria-controls="navbarScroll" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarScroll">
      <ul class="navbar-nav me-auto my-2 my-lg-0 navbar-nav-scroll" style="--bs-scroll-height: 100px;">
        <!--Dejar Vacio -->
      </ul>
      <div class="navbar-nav d-flex text-light">
        <li class="nav-item">
          <a class="nav-link" href="#nosotros">Nosotros</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#valores">Valores</a>
        </li>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Institucion Educativa
          </a>
          <ul class="dropn dropdown-menu">
            <li><a class="dropdown-item" href="#Aprendizaje">Plan de Aprendizaje</a></li>
            <li><a class="dropdown-item" href="#Cursos">Cursos</a></li>
          </ul>
        </li>        
      </div>
    </div>
  </div>
</nav>


<div id="carouselExampleCaptions" class="carousel slide" data-bs-ride="false">
    <div class="carousel-inner">
      <div class="carousel-item active">
        <img src="view/static/img/ftoportada.jpeg" class="d-block w-100" alt="...">        
      </div>
    </div>
</div>

<div class="titlev text-center" id="nosotrosv"><label for="" class="text-center">
    <h1></h1>
  </label>
</div>

<div class="title text-end" id="nosotros"><label for="">
    <h1 id="titletext" class="position-relative">NOSOTROS</h1>
  </label>
</div>

<div class="nososa card mb-3 mx-4">
  <div class="row g-0">
    <div class="col-md-4">
      <img src="view/static/img/home.jpg" class="figure-img img-fluid rounded" alt="...">

    </div>
    <div class="nosos col col-md-8">
      <div class="card-body">
        <p class="card-text text-justify">Somos conscientes de ser fuente de iniciativas y propuestas innovadoras a
          fin de satisfacer las exigencias propias de los cambios constantes que nuestros estudiantes necesitan para
          la formación de su persona.
          La calidad de nuestro​s servicios es inculcar valores y conocimiento para que nuestros estudiantes al
          finalizar su educación básica sean estudiantes críticos y reflexivos definiéndolo como persona prepara
          para
          afrontar otra etapa de su vida.</p>
        <p class="card-text text-justify">Producto de nuestro servicio y gracias a nuestros maestros, padres de
          familia y estuantes hemos logrado ocupar meritorios puestos en conocimiento y disciplina a nivel regional
          y
          nacional(CONAMAT-LIMA-BECA18, entre otros). Gracias por vuestra preferencia a esta Institución Educativa
          “Leonard Euler” donde compartimos dificultades, logros, aspiraciones y búsquedas de nuevos conocimientos y
          practica de buenos hábitos para ser cada día mejor.</p>
      </div>
    </div>
  </div>
</div>

<div class="titlev text-center" id="nosotrosv"><label for="" class="text-center">
    <h1></h1>
  </label>
</div>

<div class="title text-center mt-1" id="valores"><label for="" class="text-center">
    <h1 id="titletext2" class="position-relative">NUESTROS VALORES</h1>
  </label>
</div>

<div class="row row-cols-1 row-cols-md-3 g-4 mx-4">
  <div class="col p-3">
    <div class="cardv card h-100 text-center">
      <div class="card-body mb-2">
        <img src="view/static/img/2856361.png" alt="">
        <hr>
        <h2 class="card-title">MISIÓN</h2>
        <hr>
        <p class="card-text">Preparar al estudiante de manera integral y eficiente en forma progresiva desde inicial
          hasta el nivel Secundario. Que sean capaces de resolver problemas del entorno considerándose buen
          ciudadano
          para la vida y la sociedad.</p>
      </div>
    </div>
  </div>
  <div class="col p-3">
    <div class="cardv card h-100 text-center">
      <div class="card-body">
        <img src="view/static/img/2.png" alt="">
        <hr>
        <h2 class="card-title">VISIÓN</h2>
        <hr>
        <p class="card-text">Convertirnos en líder de la educación de Pátapo y de la Región, porque contamos con un
          potencial humano capacitado que garantiza la formación integral del estudiante. Continuar mejorando los
          conocimientos, el material didáctico y la infraestructura para el desarrollo de sus actividades de manera
          eficiente.</p>
      </div>
    </div>
  </div>
  <div class="col p-3">
    <div class="cardv card h-100 text-center">
      <div class="card-body">
        <img src="view/static/img/3.png" alt="">
        <hr>
        <h2 class="card-title">VALORES</h2>
        <hr>
        <p class="card-text">Nuestro proyecto Educativo tiene como meta la formación integral del estudiante, tanto
          en
          lo académico como en lo personal, valores como la Responsabilidad, Puntualidad, Respeto, Trabajo y
          Tolerancias son pilares básicos que sostienen nuestra tarea como docente. </p>
      </div>
    </div>
  </div>
</div>

<div class="titlev text-center" id="nosotrosv"><label for="" class="text-center">
    <h1><!----Vacio--></h1>
  </label>
</div>


<div class="title text-center" id="Aprendizaje"><label for="" class="text-center">
    <h1 id="titletext3" class="position-relative">PLAN DE APRENDIZAJE</h1>
  </label>
</div>

<div class="container">
  <div class="row row-cols-1 row-cols-md-2 g-4 mx-4">
    <div class="col">
      <div class="cardp card h-100">
        <div class="card-body">
          <h2 class="card-title text-center">INICIAL</h2>
          <hr>
          <p class="card-text">El proceso formativo en Educación Inicial, se basa en una metodología activa respetando
            sus etapas y desarrollo, reconociendo sus intereses, necesidades,habilidades y ritmos de aprendizaje.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="cardp card h-100">
        <div class="card-body">
          <h2 class="card-title text-center">PRIMARIA</h2>
          <hr>
          <p class="card-text">La propuesta educativa se centra la labor educativa de una tutoría de calidad.
            Establecemos una relación directa y cercana, de escucha y acogida con cada uno de nuestros estudiantes, el
            cual nos permite orientarlas en su proceso de crecimiento académico y realización personal.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="cardp card h-100">
        <div class="card-body">
          <h2 class="card-title text-center">SECUNDARIA</h2>
          <hr>
          <p class="card-text">El programa del Nivel de Educación Secundaria está diseñado para promover capacidades y
            competencias en los estudiantes para el logro de aprendizajes pertinentes. Se desarrolla el pensamiento
            crítico para generar soluciones socialmente responsables.</p>
        </div>
      </div>
    </div>
    <div class="col">
      <div class="cardp card h-100">
        <div class="card-body">
          <h2 class="card-title text-center">CEBA</h2>
          <hr>
          <p class="card-text">El plan de aprendizaje CEBA tiene por finalidad acercar a los estudiantes hacia una
            actitud universitaria o técnica, en la que predominen la madurez y la vocación por el estudio,
            preparándolos
            para asumir con éxito la formación profesional.</p>
        </div>
      </div>
    </div>
  </div>
</div>

<div class="titlev text-center" id="nosotrosv"><label for="" class="text-center">
    <h1><!----Vacio--></h1>
  </label>
</div>


<div class="title text-center" id="Cursos"><label for="" class="text-center">
  <h1 id="titletext4" class="position-relative">CURSOS</h1>
</label></div>

<div class="container">
  <div class="accordion px-5" id="accordionExampleEBR">
    <div class="accordion-item text-center">
      <h2 class="accordion-header" id="headingThree">
        <button class="collapsed accordion-button" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOneEBR" aria-controls="collapseOne">
          <h1>Institucion Educativa</h1>
        </button>
      </h2>
      <div id="collapseOneEBR" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExampleEBR">
        <div class="accordion-body">
          <div class="container text-center">
            <div class="row">
              <div class="col">
                <div class="accordion my-2 my-md-0" id="accordionExampleMateEBR">
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOneMateEBR" aria-expanded="true" aria-controls="collapseOne">
                        Matematica
                      </button>
                    </h2>
                    <div id="collapseOneMateEBR" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExampleMateEBR">
                      <div class="accordion-body">
                        <div class="row">
                          <div class="col">
                              Álgebra
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              Geometría
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              Aritmética
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="accordion my-2 my-md-0" id="accordionExampleComEBR">
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOneComEBR" aria-expanded="true" aria-controls="collapseOne">
                        Comunicación
                      </button>
                    </h2>
                    <div id="collapseOneComEBR" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExampleComEBR">
                      <div class="accordion-body">
                        <div class="row">
                          <div class="col">
                              Literatura
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              Geometría
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              Aritmética
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="accordion my-2 my-md-0" id="accordionExampleBioEBR">
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOneBioEBR" aria-expanded="true" aria-controls="collapseOne">
                        Biologia
                      </button>
                    </h2>
                    <div id="collapseOneBioEBR" class="accordion-collapse collapse " aria-labelledby="headingOne" data-bs-parent="#accordionExampleBioEBR">
                      <div class="accordion-body">
                        <div class="row">
                          <div class="col">
                              Álgebra
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              Geometría
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              Aritmética
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="accordion my-2 my-md-0" id="accordionExampleFomEBR">
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOneFomEBR" aria-expanded="true" aria-controls="collapseOne">
                        Formacion Laboral
                      </button>
                    </h2>
                    <div id="collapseOneFomEBR" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExampleFomEBR">
                      <div class="accordion-body">
                        <div class="row">
                          <div class="col">
                              Álgebra
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              Geometría
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              Aritmética
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>          
          </div>          
        </div>
      </div>
    </div>
    <div class="accordion-item">
      <h2 class="accordion-header" id="headingTwo">
        <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseTwoEBA" aria-expanded="false" aria-controls="collapseTwo">
          <h1>Academia</h1>
        </button>
      </h2>
      <div id="collapseTwoEBA" class="accordion-collapse collapse" aria-labelledby="headingTwo" data-bs-parent="#accordionExampleEBA">
        <div class="accordion-body">
          <div class="container text-center">
            <div class="row">
              <div class="col">
                <div class="accordion my-2 my-md-0" id="accordionExampleMatEBA">
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOneMatEBA" aria-expanded="true" aria-controls="collapseOne">
                        Matematica
                      </button>
                    </h2>
                    <div id="collapseOneMatEBA" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExampleMatEBA">
                      <div class="accordion-body">
                        <div class="row">
                          <div class="col">
                              Álgebra
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              Geometría
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              Aritmética
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="accordion my-2 my-md-0" id="accordionExampleComEBA">
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOneComEBA" aria-expanded="true" aria-controls="collapseOne">
                        Comunicación
                      </button>
                    </h2>
                    <div id="collapseOneComEBA" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExampleComEBA">
                      <div class="accordion-body">
                        <div class="row">
                          <div class="col">
                              Literatura
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              Geometría
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              Aritmética
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
              <div class="col">
                <div class="accordion my-2 my-md-0" id="accordionExampleBioEBA">
                  <div class="accordion-item">
                    <h2 class="accordion-header" id="headingOne">
                      <button class="accordion-button collapsed" type="button" data-bs-toggle="collapse" data-bs-target="#collapseOneBioEBA" aria-expanded="true" aria-controls="collapseOne">
                        Biologia
                      </button>
                    </h2>
                    <div id="collapseOneBioEBA" class="accordion-collapse collapse" aria-labelledby="headingOne" data-bs-parent="#accordionExampleBioEBA">
                      <div class="accordion-body">
                        <div class="row">
                          <div class="col">
                              Álgebra
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              Geometría
                          </div>
                        </div>
                        <div class="row">
                          <div class="col">
                              Aritmética
                          </div>
                        </div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>          
          </div>
        </div>
      </div>
    </div>    
  </div>
</div>

<div class="titlev text-center" id="nosotrosv"><label for="" class="text-center">
    <h1><!----Vacio--></h1>
  </label>
</div>


<div class="title text-center" id="Album"><label for="" class="text-center">
  <h1 id="titletext5" class="position-relative">ALBUM</h1>
</label></div>

<section class="album">
    <div class="contenedorAlbum" id="listarAlbum">
      <!-- albúm -->
    </div>
    <div class="paginasAlbum" id="paginacion">
      <!-- paginación -->
    </div>
    <div class="albumCelular hidden">
      
      <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
        <ol class="carousel-indicators">
          <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
          <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
        </ol>
        <div class="carousel-inner">
          <div class="carousel-item active">
            <img class="d-block w-100" src="view/static/albumImg/portada.jpg" alt="First slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="view/static/albumImg/portada.jpg" alt="Second slide">
          </div>
          <div class="carousel-item">
            <img class="d-block w-100" src="view/static/albumImg/portada.jpg" alt="Third slide">
          </div>
        </div>
        <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
          <span class="carousel-control-prev-icon" aria-hidden="true"></span>
          <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
          <span class="carousel-control-next-icon" aria-hidden="true"></span>
          <span class="sr-only">Next</span>
        </a>
      </div>

    </div>
  </div>
</section>

<div class="titlev text-center" id="nosotrosv"><label for="" class="text-center">
    <h1><!----Vacio--></h1>
  </label>
</div>


<div class="title text-center" id="Equipo"><label for="" class="text-center">
  <h1 id="titletext6" class="position-relative">EQUIPO</h1>
</label></div> 


<div class="container">
    <div class=" card-body">
      <div class="row row-cols-1 row-cols-md-4 g-4 mx-4 text-center my-5">
        <div class="col">
          <div class="carde card h-100">
            <img src="view/static/img/perfil.jpg" class="card-img-top" alt="...">
            <!-- <rect with="100%" hieght="100%"></rect> -->
            <div class="card-body">
              <h5 class="card-title">Juan de la Cruz Bustamante Nuñez</h5>
              <p class="card-text">Director</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="carde card h-100">
            <img src="view/static/img/perfil.jpg" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">Gladys Beatriz Sanchez Bustamante</h5>
              <p class="card-text">Promotora</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="carde card h-100">
            <img src="view/static/img/perfil.jpg" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">Alex Fabian Sanchez Bustamante</h5>
              <p class="card-text">Secretario</p>
            </div>
          </div>
        </div>
        <div class="col">
          <div class="carde card h-100">
            <img src="view/static/img/perfil.jpg" class="card-img-top" alt="...">
            <div class="card-body">
              <h5 class="card-title">Consuelo Bustamante Gálvez</h5>
              <p class="card-text">Tesorera</p>
            </div>
          </div>
        </div>
      </div> 
    </div>
  </div>
</div>


<div class="footer card text-bg-dark" >
  <div class="card-body">
    <div class="container">
      <footer>        
        <div class="row">
          <div class="col mx-md-5 my-4">
            <span class="text-center"><h5>Contactanos</h5></span>
            <hr>
            <h5 class="mx-4">Dirección</h5>
            <ul class="nav flex-column mx-4">
              <li class="nav-item mb-2">Av. La Rivera 02, Patapo - Posope Alto</li>
            </ul>
            <h5 class="mx-4">Celular</h5>
            <ul class="nav flex-column mx-4">
              <li class="nav-item mb-2">+51 968 845 397</li>
              <li class="nav-item mb-2">+51 968 837 602</li>             
            </ul>
            <h5 class="mx-4">Telefono</h5>
            <ul class="nav flex-column mx-4">
              <li class="nav-item mb-2">074 428028</li>
              <li class="nav-item mb-2">074 428117</li>           
            </ul>                     
            <h5 class="mx-4">Correo</h5>
            <ul class="nav flex-column mx-4">
              <li class="nav-item mb-2">colegio_leonard_euler@hotmail.com</li>           
            </ul>                 
          </div>  

          <div class="col my-4">
            <span class="text-center"><h5>Atencion al cliente</h5></span>
            <hr>
            <div class="my-5 rounded-4 card mx-1 text-center" style="background-color: rgba(33, 33, 33,1);">
              <div class="">
                <div class="rounded-5 table-responsive">
                  <table class="table table-bordered m-0" style="color: #fff;">
                    <thead>
                      <tr>
                        <th scope="col">#</th>
                        <th scope="col"><h3>Lunes a Viernes</h3></th>
                        <th scope="col"><h3>Sabado</h3></th>      
                      </tr>
                    </thead>
                    <tbody>
                      <tr>
                        <th><h3>Dia</h3></th>
                        <td><h4>8:00 a 12:45</h4></td>
                        <td><h4>9:00 a 11:00</h4></td>
                      </tr>
                      <tr>
                        <th><h3>Tarde</h3></th>
                        <td><h4>16:00 a 18:00</h4></td>   
                        <td><h4>----</h4></td>
                      </tr>            
                    </tbody>
                  </table> 
                </div>                
              </div>   
            </div>
          </div>
        
        
    
        <div class="d-flex justify-content-between border-top pt-2">
          <p>&copy; 2022 LEONARD E​​ULER Derechos Reservados</p>
          <ul class="list-unstyled d-flex">
            <li class="ms-3"><a href="https://wa.link/0vg48i" target="_blank"><i  class="fa-brands fa-whatsapp fa-2x"></i></a></li>     
            <li class="ms-3"><a href="https://wa.link/551yzr" target="_blank"><i class="fa-brands fa-whatsapp fa-2x"></i></a></li>  
            <li class="ms-3"><a href="https://www.facebook.com/iepleonardeuler" target="_blank"><i class="fa-brands fa-facebook fa-2x"></i></a></li>          
          </ul>
        </div>
      </footer>        
    </div>
  </div>   
  
</div>
<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
  integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
  crossorigin="anonymous"></script>
