<!DOCTYPE html>
<html style="font-size: 16px;" lang="es"><head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta charset="UTF-8">
    <meta name="keywords" content="Innovative Car Wash System, About, Premium Hand Car Wash &amp;amp; Detail">
    <meta name="description" content="">
    <title>Inicio</title>
    <link rel="stylesheet" href="nicepage.css" media="screen">
    <link rel="stylesheet" href="Inicio.css" media="screen">
    <script class="u-script" type="text/javascript" src="jquery.js" defer=""></script>
    <script class="u-script" type="text/javascript" src="nicepage.js" defer=""></script>
    <meta name="generator" content="Nicepage 4.19.5, nicepage.com">
    <link id="u-theme-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Roboto:100,100i,300,300i,400,400i,500,500i,700,700i,900,900i|Open+Sans:300,300i,400,400i,500,500i,600,600i,700,700i,800,800i">
    <link id="u-page-google-font" rel="stylesheet" href="https://fonts.googleapis.com/css?family=Oswald:200,300,400,500,600,700|Aclonica:400">
    
    
    <script type="application/ld+json">{
		"@context": "http://schema.org",
		"@type": "Organization",
		"name": "WebSite3052773",
		"logo": "img/logo.png"
}</script>
    <meta name="theme-color" content="#3db4df">
    <meta property="og:title" content="Inicio">
    <meta property="og:description" content="">
    <meta property="og:type" content="website">
  </head>
  <body class="u-body u-overlap u-xl-mode" data-lang="es"><header class="u-clearfix u-header u-sticky u-sticky-78f2 u-white u-header" id="sec-5c4f"><a href="Inicio.php" class="u-image u-logo u-image-1" data-image-width="1043" data-image-height="1043">
        <img src="img/logo.png" class="u-logo-image u-logo-image-1">
      </a><nav class="u-menu u-menu-one-level u-menu-open-right u-offcanvas u-offcanvas-shift u-menu-1" data-responsive-from="MD">
        <div class="menu-collapse" style="font-size: 1rem; letter-spacing: 0px;">
          <a class="u-border-2 u-border-grey-75 u-button-style u-custom-left-right-menu-spacing u-custom-padding-bottom u-custom-text-active-color u-custom-text-color u-custom-text-hover-color u-custom-top-bottom-menu-spacing u-file-icon u-grey-15 u-nav-link u-text-active-palette-1-base u-text-hover-palette-2-base u-file-icon-1" href="#">
            <img src="img/1665676.png" alt="">
          </a>
        </div>
        <div class="u-custom-menu u-nav-container">
          <ul class="u-nav u-spacing-5 u-unstyled u-nav-1">
            <li class="u-nav-item"><a class="u-border-active-grey-80 u-border-hover-grey-50 u-button-style u-nav-link u-text-active-grey-5 u-text-hover-black" href="Inicio.php#sec-0ca7" style="padding: 12px 10px;">Nostros</a>
          </li><li class="u-nav-item"><a class="u-border-active-grey-80 u-border-hover-grey-50 u-button-style u-nav-link u-text-active-grey-5 u-text-hover-black" href="Inicio.php#sec-b685" style="padding: 12px 10px;">Valores</a>
          </li><li class="u-nav-item"><a class="u-border-active-grey-80 u-border-hover-grey-50 u-button-style u-nav-link u-text-active-grey-5 u-text-hover-black" href="Inicio.php#sec-5715" style="padding: 12px 10px;">Plan de Aprendizaje</a>
          </li><li class="u-nav-item"><a class="u-border-active-grey-80 u-border-hover-grey-50 u-button-style u-nav-link u-text-active-grey-5 u-text-hover-black" href="Inicio.php#sec-bde6" style="padding: 12px 10px;">Asistencias</a>
          </li><li class="u-nav-item"><a class="u-border-active-grey-80 u-border-hover-grey-50 u-button-style u-nav-link u-text-active-grey-5 u-text-hover-black" href="Inicio.php#sec-9bd3" style="padding: 12px 10px;">Equipo</a>
          </li><li class="u-nav-item"><a class="u-border-active-grey-80 u-border-hover-grey-50 u-button-style u-nav-link u-text-active-grey-5 u-text-hover-black" href="Inicio.php#sec-0c25" style="padding: 12px 10px;">Contactanos</a>
          </li><li class="u-nav-item"><a class="u-border-active-grey-80 u-border-hover-grey-50 u-button-style u-nav-link u-text-active-grey-5 u-text-hover-black" href="/leonard_euler/login/login.php" style="padding: 12px 36px 12px 10px;">Iniciar Sesion</a>
          </li></ul>
        </div>
        <div class="u-custom-menu u-nav-container-collapse">
          <div class="u-black u-container-style u-inner-container-layout u-opacity u-opacity-95 u-sidenav">
            <div class="u-inner-container-layout u-sidenav-overflow">
              <div class="u-menu-close"></div>
              <ul class="u-align-center u-nav u-popupmenu-items u-unstyled u-nav-2"><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Inicio.html#sec-0ca7" style="padding-top: 14px; padding-bottom: 14px;">Nostros</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Inicio.php#sec-b685" style="padding-top: 14px; padding-bottom: 14px;">Valores</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Inicio.php#sec-5715" style="padding-top: 14px; padding-bottom: 14px;">Plan de Aprendizaje</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Inicio.php#sec-bde6" style="padding-top: 14px; padding-bottom: 14px;">Asistencias</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Inicio.php#sec-9bd3" style="padding-top: 14px; padding-bottom: 14px;">Equipo</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Inicio.php#sec-0c25" style="padding-top: 14px; padding-bottom: 14px;">Contactanos</a>
</li><li class="u-nav-item"><a class="u-button-style u-nav-link" href="Inicio.php#carousel_1a65" style="padding-top: 14px; padding-bottom: 14px;">Iniciar Sesion</a>
</li></ul>
            </div>
          </div>
          <div class="u-black u-menu-overlay u-opacity u-opacity-70"></div>
        </div>
      </nav></header> 
    <section class="skrollable u-align-center u-clearfix u-section-1" id="carousel_1a65">
      
      <div class="u-clearfix u-expanded-width u-gutter-100 u-layout-wrap u-layout-wrap-1">
        <div class="u-gutter-0 u-layout">
          <div class="u-layout-row">
            <div class="u-container-style u-gradient u-layout-cell u-size-60 u-layout-cell-1">
              <div class="u-container-layout u-container-layout-1">
                <h1 class="u-custom-font u-font-oswald u-text u-text-palette-5-light-3 u-text-1">I.E.P "LEONA​​​​RD E​ULER"</h1>
                <p class="u-text u-text-white u-text-2">PASION POR EL ESTUDIO Y ​DICSIPLINA&nbsp;</p>
                <img class="u-expanded-height-md u-expanded-height-sm u-expanded-height-xl u-expanded-height-xs u-image u-image-1" src="img/logo.png" data-image-width="1043" data-image-height="1043">
              </div>
            </div>
          </div>
        </div>
      </div>
      <img class="u-border-2 u-border-grey-75 u-expanded-width u-image u-image-default u-opacity u-opacity-30 u-image-2" src="img/WhatsAppImage2022-10-12at2.17.38PM.jpeg" alt="" data-image-width="1440" data-image-height="1080">
      <img class="u-image u-image-contain u-image-default u-preserve-proportions u-image-3" src="img/Myproject-11.png" alt="" data-image-width="1080" data-image-height="1080">
      <h1 class="u-custom-font u-font-georgia u-hover-feature u-text u-text-custom-color-9 u-text-3">AÑOS</h1>
      <div class="u-container-style u-group u-shape-rectangle u-group-1">
        <div class="u-container-layout u-container-layout-2">
          <h1 class="u-custom-font u-text u-text-custom-color-9 u-text-4">EDUCANDO A NUESTRA COMUNIDAD </h1>
          <div class="u-border-11 u-border-black u-line u-line-vertical u-opacity u-opacity-55 u-line-1"></div>
        </div>
      </div>
    </section>
    <section class="u-align-center u-clearfix u-section-2" id="sec-0ca7">
      <div class="u-clearfix u-sheet u-valign-middle-lg u-valign-middle-md u-valign-middle-sm u-sheet-1"><span class="u-file-icon u-icon u-icon-1"><img src="img/organizacion.png" alt=""></span>
        <h1 class="u-text u-text-default-xl u-text-1"> NOSOTROS SOMOS</h1>
      </div>
    </section>
    <section class="u-clearfix u-section-3" id="sec-e628">
      <div class="u-clearfix u-sheet u-valign-middle u-sheet-1">
        <div class="u-clearfix u-expanded-width-md u-expanded-width-sm u-expanded-width-xs u-gutter-0 u-layout-spacing-vertical u-layout-wrap u-layout-wrap-1">
          <div class="u-gutter-0 u-layout" style="">
            <div class="u-layout-row" style="">
              <div class="u-container-style u-layout-cell u-size-60 u-layout-cell-1">
                <div class="u-container-layout u-container-layout-1">
                  <p class="u-align-justify u-text u-text-1"> Producto de nuestro servicio y gracias a nuestros maestros,
padres de familia y estuantes hemos logrado ocupar meritorios puestos en
conocimiento y disciplina a nivel regional y nacional(CONAMAT-LIMA-BECA18, entre otros). 
Gracias por vuestra preferencia a esta Institución Educativa
“Leonard Euler” donde compartimos dificultades, logros, aspiraciones y
búsquedas de nuevos conocimientos y practica de buenos hábitos para ser cada día mejor.&nbsp;&nbsp;<br>&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;<br>
                  </p>
                  <p class="u-align-justify u-text u-text-2"> Somos
conscientes de ser fuente de iniciativas y propuestas innovadoras a fin de satisfacer
las exigencias propias de los cambios constantes que nuestros estudiantes
necesitan para la formación de su persona.&nbsp;<br> La
calidad de nuestro​s servicios es inculcar valores y conocimiento para que
nuestros estudiantes al finalizar su educación básica sean estudiantes críticos
y reflexivos definiéndolo como persona prepara para afrontar otra etapa de su
vida.&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp; &nbsp;&nbsp;
                  </p>
                  <img class="u-image u-image-1" data-image-width="256" data-image-height="256" src="data:image/svg+xml;base64,PHN2ZyB2ZXJzaW9uPSIxLjEiIGlkPSJtYW4iIHhtbG5zPSJodHRwOi8vd3d3LnczLm9yZy8yMDAwL3N2ZyIgeD0iMHB4IiB5PSIwcHgiIHZpZXdCb3g9IjAgMCAyNTYgMjU2IiBzdHlsZT0id2lkdGg6IDI1NnB4OyBoZWlnaHQ6IDI1NnB4OyI+CjxyZWN0IGZpbGw9IiNDNkQ4RTEiIHdpZHRoPSIyNTYiIGhlaWdodD0iMjU2Ii8+CjxwYXRoIGZpbGw9IiM3Rjk2QTYiIGQ9Ik0xNzIuNiw5My40YzExLjYtNDQuNy0xMS4yLTQ4LjYtMTEuNy00OC4xYy0yMi40LTMxLjMtOTAuMy0xNi44LTc3LjQsNDguMWMtMTMuMy0yLjQtMS44LDMxLjYsMy43LDMyLjEKCWMwLDAsMCwwLDAsMGMwLjIsMCwwLjMsMCwwLjUtMC4xYzE0LjQsNDkuNyw2Mi43LDUwLjIsODAuNywwQzE3Mi4zLDEyNy4zLDE4Ni41LDkzLjMsMTcyLjYsOTMuNHoiLz4KPHBhdGggZmlsbD0iIzdGOTZBNiIgZD0iTTIwNS40LDE3Ny45Yy0yNC02LjEtNDMuNS0xOS44LTQzLjUtMTkuOGwtMjAuNiw2NC44bC04LTIyLjhjMTkuNy0yNy41LTMwLjMtMjcuNS0xMC42LDBsLTgsMjIuOEw5NCwxNTguMQoJYzAsMC0xOS41LDEzLjctNDMuNSwxOS44QzMyLjcsMTgyLjUsMzAsMjU2LDMwLDI1NmgxOTZDMjI2LDI1NiwyMjMuMywxODIuNSwyMDUuNCwxNzcuOXoiLz4KPC9zdmc+Cg==">
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="u-align-center u-clearfix u-section-4" id="sec-b685">
      <div class="u-clearfix u-sheet u-valign-middle-lg u-valign-middle-xl u-valign-middle-xs u-sheet-1"><span class="u-file-icon u-icon u-icon-1"><img src="img/3050482.png" alt=""></span>
        <h1 class="u-text u-text-default-lg u-text-default-md u-text-default-sm u-text-default-xl u-text-1">NUESTROS VALORES<br>
        </h1>
      </div>
    </section>
    <section class="u-align-center u-clearfix u-section-5" id="sec-b9f8">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-expanded-width-lg u-expanded-width-md u-expanded-width-xl u-list u-list-1">
          <div class="u-repeater u-repeater-1">
            <div class="u-border-2 u-border-black u-container-style u-gradient u-hover-feature u-list-item u-radius-10 u-repeater-item u-shape-round u-video-cover u-list-item-1">
              <div class="u-container-layout u-similar-container u-container-layout-1"><span class="u-file-icon u-icon u-icon-1"><img src="img/2856361.png" alt=""></span>
                <h5 class="u-align-center u-text u-text-default u-text-1">MISIÓN </h5>
                <p class="u-align-justify u-text u-text-2"> Preparar al estudiante de manera integral y eficiente en
forma progresiva desde inicial hasta el nivel Secundario. Que sean capaces de
resolver problemas del entorno considerándose buen ciudadano para la vida y la
sociedad.</p>
              </div>
            </div>
            <div class="u-border-2 u-border-black u-container-style u-gradient u-hover-feature u-list-item u-radius-10 u-repeater-item u-shape-round u-list-item-2">
              <div class="u-container-layout u-similar-container u-container-layout-2"><span class="u-file-icon u-icon u-icon-2"><img src="img/8358078.png" alt=""></span>
                <h5 class="u-align-center u-text u-text-default u-text-3">VISI​ÓN</h5>
                <p class="u-align-justify u-text u-text-4"> Convertirnos en líder de la educación de Pátapo y de la
Región, porque contamos con un potencial humano capacitado que garantiza la
formación integral del estudiante. Continuar mejorando los conocimientos, el
material didáctico y la infraestructura para el desarrollo de sus actividades
de manera eficiente. &nbsp;</p>
              </div>
            </div>
            <div class="u-border-2 u-border-black u-container-style u-gradient u-hover-feature u-list-item u-radius-10 u-repeater-item u-shape-round u-video-cover u-list-item-3">
              <div class="u-container-layout u-similar-container u-container-layout-3"><span class="u-file-icon u-icon u-icon-3"><img src="img/3391424.png" alt=""></span>
                <h5 class="u-align-center u-text u-text-default u-text-5"> VALORES</h5>
                <p class="u-align-justify u-text u-text-6">Nuestro proyecto Educativo tiene como meta la formación
integral del estudiante, tanto en lo académico como en lo personal, valores
como la Responsabilidad, Puntualidad, Respeto, Trabajo y Tolerancias son
pilares básicos que sostienen nuestra tarea como docente.&nbsp;&nbsp;</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      
      
    </section>
    <section class="u-align-center u-clearfix u-section-6" id="sec-5715">
      <div class="u-clearfix u-sheet u-valign-middle-lg u-valign-middle-md u-valign-middle-sm u-valign-middle-xl u-sheet-1">
        <h1 class="u-text u-text-default-lg u-text-default-md u-text-default-sm u-text-default-xl u-text-1">PLAN DE APRENDIZAJE&nbsp;</h1><span class="u-file-icon u-icon u-icon-1"><img src="img/3429417.png" alt=""></span>
      </div>
    </section>
    <section class="u-align-center u-clearfix u-section-7" id="sec-00d9">
      <div class="u-clearfix u-sheet u-sheet-1">
        <div class="u-expanded-width-lg u-expanded-width-md u-expanded-width-xl u-expanded-width-xs u-layout-grid u-list u-list-1">
          <div class="u-repeater u-repeater-1">
            <div class="u-align-left u-container-style u-custom-item u-gradient u-hover-feature u-list-item u-repeater-item u-video-cover u-list-item-1">
              <div class="u-container-layout u-similar-container u-container-layout-1">
                <p class="u-text u-text-default u-text-1">INICIAL</p>
                <p class="u-text u-text-default u-text-2">El proceso formativo en Educación Inicial, se basa en una metodología activa respetando sus etapas y desarrollo, reconociendo sus intereses, necesidades,habilidades y ritmos de aprendizaje.</p>
              </div>
            </div>
            <div class="u-align-left u-container-style u-custom-item u-gradient u-hover-feature u-list-item u-repeater-item u-video-cover u-list-item-2">
              <div class="u-container-layout u-similar-container u-container-layout-2">
                <p class="u-text u-text-default u-text-3">PRIMARIA</p>
                <p class="u-text u-text-default u-text-4"> La propuesta educativa se centra la labor educativa de una tutoría de calidad. Establecemos una relación directa y cercana, de escucha y acogida con cada uno de nuestros estudiantes, el cual nos permite orientarlas en su proceso de crecimiento académico y realización personal.</p>
              </div>
            </div>
            <div class="u-align-left u-container-style u-custom-item u-gradient u-hover-feature u-list-item u-repeater-item u-video-cover u-list-item-3">
              <div class="u-container-layout u-similar-container u-container-layout-3">
                <p class="u-text u-text-default u-text-5">SECUNDARIA</p>
                <p class="u-text u-text-default u-text-6"> El programa del Nivel de Educación Secundaria está diseñado para promover capacidades y competencias en los estudiantes para el logro de aprendizajes pertinentes. Se desarrolla el pensamiento crítico para generar soluciones socialmente responsables.</p>
              </div>
            </div>
            <div class="u-align-left u-container-style u-custom-item u-gradient u-hover-feature u-list-item u-repeater-item u-video-cover u-list-item-4">
              <div class="u-container-layout u-similar-container u-container-layout-4">
                <p class="u-text u-text-default u-text-7">CEBA</p>
                <p class="u-text u-text-default u-text-8">El plan de aprendizaje CEBA tiene por finalidad acercar a los estudiantes hacia una actitud universitaria o técnica, en la que predominen la madurez y la vocación por el estudio, preparándolos para asumir con éxito la formación profesional.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
      
      
      
      
    </section>
    <section class="u-align-center u-clearfix u-section-8" id="sec-bde6">
      <div class="u-align-left u-clearfix u-sheet u-valign-middle-md u-valign-middle-xs u-sheet-1"><span class="u-file-icon u-icon u-icon-1"><img src="img/pautas.png" alt=""></span>
        <h1 class="u-align-center u-text u-text-1">REGISTRO DE ASISTENCIA</h1>
      </div>
    </section>
    <section class="u-clearfix u-section-9" id="sec-9541">
      <div class="u-clearfix u-sheet u-valign-middle-lg u-valign-middle-xl u-valign-top-xs u-sheet-1">
        <div class="u-container-style u-group u-preserve-proportions u-shape-rectangle u-group-1">
          <div class="u-container-layout u-container-layout-1">
            <a href="https://nicepage.com/static-site-generator" class="u-border-7 u-border-active-custom-color-2 u-border-grey-75 u-border-hover-custom-color-2 u-btn u-btn-round u-button-style u-palette-4-light-2 u-radius-30 u-text-grey-90 u-btn-1"> INICIAL</a>
            <a href="https://nicepage.com/static-site-generator" class="u-align-left-md u-align-left-sm u-align-left-xs u-border-7 u-border-active-custom-color-2 u-border-grey-75 u-border-hover-custom-color-2 u-btn u-btn-round u-button-style u-hover-feature u-palette-4-light-2 u-radius-30 u-text-grey-90 u-btn-2">PRIMARIA</a>
            <a href="https://nicepage.com/static-site-generator" class="u-border-7 u-border-active-custom-color-2 u-border-grey-75 u-border-hover-custom-color-2 u-btn u-btn-round u-button-style u-palette-4-light-2 u-radius-30 u-text-grey-90 u-btn-3">SECUNDARIA</a>
          </div>
        </div>
      </div>
      
    </section>
    <section class="u-align-center u-clearfix u-section-10" id="sec-9bd3">
      <div class="u-clearfix u-sheet u-valign-middle-xs u-sheet-1"><span class="u-file-icon u-icon u-icon-1"><img src="img/trabajo-en-equipo.png" alt=""></span>
        <h1 class="u-text u-text-default-lg u-text-default-md u-text-default-sm u-text-default-xl u-text-1"> Miembro del equipo&nbsp;</h1>
      </div>
    </section>
    <section class="u-clearfix u-section-11" id="sec-0ce5">
      <div class="u-clearfix u-sheet u-valign-middle-lg u-valign-middle-sm u-valign-middle-xs u-sheet-1">
        <div class="u-expanded-width-md u-expanded-width-sm u-expanded-width-xs u-list u-list-1">
          <div class="u-repeater u-repeater-1">
            <div class="u-align-center u-container-style u-list-item u-repeater-item">
              <div class="u-container-layout u-similar-container u-container-layout-1">
                <div alt="" class="u-image u-image-circle u-image-1" src="" data-image-width="500" data-image-height="500"></div>
                <h5 class="u-align-center-lg u-align-center-md u-align-center-sm u-align-center-xs u-text u-text-1">Juan de la Cruz Bustamante Nuñez</h5>
                <p class="u-align-center-lg u-align-center-md u-align-center-sm u-align-center-xs u-text u-text-2">Director</p>
              </div>
            </div>
            <div class="u-align-center u-container-style u-list-item u-repeater-item">
              <div class="u-container-layout u-similar-container u-container-layout-2">
                <div alt="" class="u-image u-image-circle u-image-2" src="" data-image-width="500" data-image-height="500"></div>
                <h5 class="u-align-center-lg u-align-center-md u-align-center-sm u-align-center-xs u-text u-text-3">Gladys Beatriz Sanchez Bustamante</h5>
                <p class="u-align-center-lg u-align-center-md u-align-center-sm u-align-center-xs u-text u-text-4">Promotora</p>
              </div>
            </div>
            <div class="u-align-center u-container-style u-list-item u-repeater-item">
              <div class="u-container-layout u-similar-container u-container-layout-3">
                <div alt="" class="u-image u-image-circle u-image-3" src="" data-image-width="500" data-image-height="500"></div>
                <h5 class="u-align-center-lg u-align-center-md u-align-center-sm u-align-center-xs u-text u-text-5">Alex Fabian Sanchez Bustamante</h5>
                <p class="u-align-center-lg u-align-center-md u-align-center-sm u-align-center-xs u-text u-text-6">Secretario</p>
              </div>
            </div>
            <div class="u-align-center u-container-style u-list-item u-repeater-item">
              <div class="u-container-layout u-similar-container u-container-layout-4">
                <div alt="" class="u-image u-image-circle u-image-4" src="" data-image-width="500" data-image-height="500"></div>
                <h5 class="u-align-center-lg u-align-center-md u-align-center-sm u-align-center-xs u-text u-text-7">Alex Fabian Sanchez Bustamante</h5>
                <p class="u-align-center-lg u-align-center-md u-align-center-sm u-align-center-xs u-text u-text-8">Secretario</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>
    <section class="u-align-center u-clearfix u-grey-50 u-section-12" id="sec-0c25">
      <div class="u-clearfix u-sheet u-valign-middle-lg u-valign-middle-md u-valign-middle-xl u-valign-middle-xs u-sheet-1">
        <h1 class="u-custom-font u-font-georgia u-text u-text-default-lg u-text-default-md u-text-default-xl u-text-1">Contactanos</h1>
      </div>
    </section>
    <section class="u-clearfix u-grey-50 u-section-13" id="sec-1a08">
      
      
      
      <div class="u-clearfix u-sheet u-valign-top-md u-sheet-1">
        <div class="u-container-style u-expanded-width-md u-expanded-width-sm u-expanded-width-xs u-group u-shape-rectangle u-group-1">
          <div class="u-container-layout u-container-layout-1">
            <a href="https://www.facebook.com/iepleonardeuler" class="u-btn u-button-style u-hover-feature u-none u-text-palette-5-dark-1 u-btn-1" target="_blank"> .&nbsp;<span class="u-file-icon u-icon u-icon-1"><img src="img/733547.png" alt=""></span>
            </a>
            <p class="u-text u-text-body-color u-text-1"><span class="u-file-icon u-icon u-text-black u-icon-2"><img src="img/3037821-501b5820.png" alt=""></span>Dirección:
            </p>
            <p class="u-text u-text-default u-text-2"> Av. La Rivera 02, Patapo 14610</p>
            <p class="u-text u-text-body-color u-text-3"><span class="u-file-icon u-icon u-text-black u-icon-3"><img src="img/455604-382900a4.png" alt=""></span>&nbsp;Teléfono:
            </p>
            <a href="https://wa.link/0vg48i" class="u-border-none u-btn u-button-style u-hover-feature u-none u-text-palette-5-dark-1 u-btn-2" target="_blank"><span class="u-file-icon u-icon u-icon-4"><img src="img/5968841.png" alt=""></span>&nbsp;.
            </a>
            <p class="u-text u-text-default u-text-4"> +51 968 845 397 -&nbsp;+51 968 837 602</p>
            <p class="u-text u-text-body-color u-text-5"><span class="u-file-icon u-icon u-text-black u-icon-5"><img src="img/482138-dbb28319.png" alt=""></span>&nbsp;Corr​eo:
            </p>
            <p class="u-text u-text-default u-text-6">colegio_leonard_euler@hotmail.com</p>
            <a href="https://wa.link/551yzr" class="u-border-none u-btn u-button-style u-hover-feature u-none u-text-palette-5-dark-1 u-btn-3" target="_blank"><span class="u-file-icon u-icon u-icon-6"><img src="img/5968841.png" alt=""></span>&nbsp;.
            </a>
          </div>
        </div>
        <div class="u-expanded-width-xs u-form u-grey-15 u-form-1">
          <form method="post" action="correo.php" class="u-clearfix u-form-spacing-5 u-form-vertical u-inner-form" source="email" name="form" style="padding: 4px;">
            <div class="u-form-group u-form-name">
              <label for="name-4e1a" class="u-label u-label-1">Nombre</label>
              <input type="text" placeholder="Introduzca su nombre" id="name-4e1a" name="name" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-white u-input-1" required="" autofocus="autofocus">
            </div>
            <div class="u-form-email u-form-group">
              <label for="email-4e1a" class="u-label u-label-2">Email</label>
              <input type="email" placeholder="Introduzca una dirección de correo electrónico válida" id="email-4e1a" name="email" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-white u-input-2" required="">
            </div>
            <div class="u-form-group u-form-message">
              <label for="message-4e1a" class="u-label u-label-3">Mensaje</label>
              <textarea placeholder="Ingrese su mensaje" rows="4" cols="50" id="message-4e1a" name="mensaje" class="u-border-1 u-border-grey-30 u-input u-input-rectangle u-white u-input-3" required=""></textarea>
            </div>
            <div class="u-align-left u-form-group u-form-submit">
              <a class="u-btn u-btn-submit u-button-style u-hover-palette-1-dark-1 u-palette-1-base u-btn-4">Enviar</a>
              <input type="submit" value="submit" class="u-form-control-hidden" name="enviar">
            </div>
            <div class="u-form-send-message u-form-send-success"> Gracias! Tu mensaje ha sido enviado. </div>
            <div class="u-form-send-error u-form-send-message"> No se puede enviar su mensaje. Por favor, corrija los errores y vuelva a intentarlo. </div>
            <input type="hidden" value="" name="recaptchaResponse">
            <input type="hidden" name="formServices" value="640f05a597fae9b037958c21f5d3f7f6">
          </form>
            <?php 
            include("correo.php");
            ?>
        </div>
      </div>
    </section>
    
    <footer class="u-align-center u-clearfix u-footer u-grey-80 u-footer" id="sec-7295"><div class="u-align-left u-clearfix u-sheet u-sheet-1">
        <p class="u-text u-text-default u-text-1">@2022 Derechos Reservados "LEONARD E​​ULER"&nbsp;</p>
      </div></footer>  
</body></html>